//! Schema Analyzer for Salesforce SObject Describe metadata.
//!
//! This module provides a utility to analyze `SObjectDescribe` payloads,
//! extracting insights about the health, complexity, and shape of a Salesforce
//! object schema.
//!
//! # Example
//!
//! ```no_run
//! # use force::client::ForceClientBuilder;
//! # use force::experimental::SchemaAnalyzer;
//! # use force::auth::ClientCredentials;
//! # #[tokio::main]
//! # async fn main() -> anyhow::Result<()> {
//! # let auth = ClientCredentials::new("id", "secret", "url");
//! # let client = ForceClientBuilder::new().authenticate(auth).build().await?;
//! let describe = client.rest().describe("Account").await?;
//!
//! let analyzer = SchemaAnalyzer::new();
//! let insights = analyzer.analyze(&describe);
//!
//! println!("Custom Fields: {}", insights.custom_field_count);
//! println!("Formula Fields: {}", insights.formula_field_count);
//! println!("Relationship Fields: {}", insights.relationship_field_count);
//! println!("Complexity Score: {}", insights.complexity_score);
//! # Ok(())
//! # }
//! ```

use crate::api::rest::describe::{FieldType, SObjectDescribe};

/// Insights generated by the `SchemaAnalyzer`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SchemaInsights {
    /// Total number of fields on the object.
    pub total_fields: usize,
    /// Number of custom fields (ending in `__c` or marked `custom: true`).
    pub custom_field_count: usize,
    /// Number of standard fields.
    pub standard_field_count: usize,
    /// Number of required fields (not nillable and no default on create).
    pub required_field_count: usize,
    /// Number of formula fields (calculated).
    pub formula_field_count: usize,
    /// Number of relationship fields (lookup/master-detail).
    pub relationship_field_count: usize,
    /// A simple heuristic score representing schema complexity (higher is more complex).
    pub complexity_score: usize,
}

/// Utility for analyzing Salesforce schema metadata.
#[derive(Debug, Default)]
pub struct SchemaAnalyzer;

impl SchemaAnalyzer {
    /// Creates a new `SchemaAnalyzer` instance.
    #[must_use]
    pub fn new() -> Self {
        Self
    }

    /// Analyzes an `SObjectDescribe` and returns `SchemaInsights`.
    #[must_use]
    pub fn analyze(&self, describe: &SObjectDescribe) -> SchemaInsights {
        let total_fields = describe.fields.len();
        let mut custom_field_count = 0;
        let mut required_field_count = 0;
        let mut formula_field_count = 0;
        let mut relationship_field_count = 0;

        for field in &describe.fields {
            if field.custom {
                custom_field_count += 1;
            }

            if !field.nillable && !field.defaulted_on_create && field.name != "Id" {
                required_field_count += 1;
            }

            if field.calculated {
                formula_field_count += 1;
            }

            if matches!(field.type_, FieldType::Reference) {
                relationship_field_count += 1;
            }
        }

        let standard_field_count = total_fields - custom_field_count;

        // Complexity heuristic:
        // +1 for every 10 total fields
        // +2 for every custom field (customizations add complexity)
        // +5 for every formula field (impacts query perf)
        // +3 for every relationship field (joins)
        let complexity_score = (total_fields / 10)
            + (custom_field_count * 2)
            + (formula_field_count * 5)
            + (relationship_field_count * 3);

        SchemaInsights {
            total_fields,
            custom_field_count,
            standard_field_count,
            required_field_count,
            formula_field_count,
            relationship_field_count,
            complexity_score,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_support::Must;
    use serde_json::json;

    fn create_mock_describe(fields_json: &serde_json::Value) -> SObjectDescribe {
        let describe_json = json!({
            "name": "Account",
            "label": "Account",
            "custom": false,
            "queryable": true,
            "activateable": false, "createable": true, "customSetting": false, "deletable": true,
            "deprecatedAndHidden": false, "feedEnabled": true, "hasSubtypes": false,
            "isSubtype": false, "keyPrefix": "001", "labelPlural": "Accounts", "layoutable": true,
            "mergeable": true, "mruEnabled": true, "replicateable": true, "retrieveable": true,
            "searchable": true, "triggerable": true, "undeletable": true, "updateable": true,
            "urls": {}, "childRelationships": [], "recordTypeInfos": [],
            "fields": fields_json.clone()
        });
        serde_json::from_value(describe_json).must()
    }

    #[allow(clippy::fn_params_excessive_bools)]
    fn mock_field(
        name: &str,
        field_type: &str,
        custom: bool,
        nillable: bool,
        defaulted: bool,
        calculated: bool,
    ) -> serde_json::Value {
        json!({
            "name": name,
            "type": field_type,
            "label": format!("{} Label", name),
            "referenceTo": if field_type == "reference" { vec!["Account"] } else { vec![] },
            "custom": custom,
            "nillable": nillable,
            "defaultedOnCreate": defaulted,
            "calculated": calculated,
            // Mandatory fields filler
            "createable": true, "autoNumber": false, "aggregatable": true, "byteLength": 18,
            "cascadeDelete": false, "caseSensitive": false,
            "dependentPicklist": false, "deprecatedAndHidden": false,
            "digits": 0, "displayLocationInDecimal": false, "encrypted": false, "externalId": false,
            "filterable": true, "groupable": true, "highScaleNumber": false, "htmlFormatted": false,
            "idLookup": true, "length": 18, "nameField": false, "namePointing": false,
            "permissionable": false, "polymorphicForeignKey": false, "precision": 0, "queryByDistance": false,
            "restrictedDelete": false, "restrictedPicklist": false, "scale": 0, "soapType": "tns:ID",
            "sortable": true, "unique": false, "updateable": false, "writeRequiresMasterRead": false
        })
    }

    #[test]
    fn test_schema_analyzer() {
        let describe = create_mock_describe(&json!([
            // Id: Standard, Not required (because it's Id, handled by SFDC)
            mock_field("Id", "id", false, false, true, false),
            // Name: Standard, Required (not nillable, no default)
            mock_field("Name", "string", false, false, false, false),
            // CustomField__c: Custom, Not required (nillable)
            mock_field("CustomField__c", "string", true, true, false, false),
            // Formula__c: Custom, Formula
            mock_field("Formula__c", "double", true, true, false, true),
            // ParentId: Standard, Lookup
            mock_field("ParentId", "reference", false, true, false, false),
            // CustomLookup__c: Custom, Required Lookup
            mock_field("CustomLookup__c", "reference", true, false, false, false)
        ]));

        let analyzer = SchemaAnalyzer::new();
        let insights = analyzer.analyze(&describe);

        assert_eq!(insights.total_fields, 6);
        assert_eq!(insights.custom_field_count, 3);
        assert_eq!(insights.standard_field_count, 3);
        // Required: Name, CustomLookup__c (Id is excluded by logic)
        assert_eq!(insights.required_field_count, 2);
        assert_eq!(insights.formula_field_count, 1);
        assert_eq!(insights.relationship_field_count, 2);

        // Score logic:
        // (total/10) = 0
        // (custom*2) = 6
        // (formula*5) = 5
        // (relationship*3) = 6
        // Total = 17
        assert_eq!(insights.complexity_score, 17);
    }
}
