//! Apex Class Generator.
//!
//! This module provides a utility to generate Apex wrapper classes (DTOs)
//! from Salesforce SObjectDescribe metadata. This is useful for cross-org
//! integrations, building strongly-typed wrappers for custom APIs, or
//! generating LWC-compatible data structures.

#[cfg(feature = "schema")]
use crate::types::describe::{FieldType, SObjectDescribe};
#[cfg(feature = "schema")]
use std::fmt::Write;

/// Generates an Apex class definition from an SObject describe result.
#[cfg(feature = "schema")]
pub fn generate_apex_class(describe: &SObjectDescribe) -> String {
    let mut out = String::with_capacity(describe.fields.len() * 128);
    write_apex_class(&mut out, describe);
    out
}

/// Writes an Apex class definition from an SObject describe result directly to a string buffer.
#[cfg(feature = "schema")]
pub fn write_apex_class(out: &mut String, describe: &SObjectDescribe) {
    let class_name = describe
        .name
        .replace("__c", "")
        .replace("__mdt", "")
        .replace("__e", "");

    let _ = writeln!(out, "/**");
    let _ = writeln!(out, " * Wrapper class for {} SObject", describe.name);
    let _ = writeln!(out, " * Generated by force-rs");
    let _ = writeln!(out, " */");
    let _ = writeln!(out, "public class {}Wrapper {{", class_name);

    let mut fields: Vec<&_> = describe.fields.iter().collect();
    fields.sort_by(|a, b| crate::schema::cmp_field_names(&a.name, &b.name));

    for field in fields {
        let apex_type = map_type(&field.type_);
        let _ = writeln!(out, "    @AuraEnabled");
        let _ = writeln!(out, "    public {} {};", apex_type, field.name);
    }

    out.push_str("}\n");
}

/// Maps a Salesforce `FieldType` to an Apex type.
#[cfg(feature = "schema")]
fn map_type(ft: &FieldType) -> &'static str {
    match ft {
        FieldType::Id | FieldType::Reference => "Id",
        FieldType::Boolean => "Boolean",
        FieldType::Int => "Integer",
        FieldType::Double | FieldType::Currency | FieldType::Percent => "Decimal",
        FieldType::Date => "Date",
        FieldType::Datetime => "Datetime",
        FieldType::Time => "Time",
        FieldType::Base64 => "Blob",
        _ => "String",
    }
}

#[cfg(test)]
#[cfg(feature = "schema")]
mod tests {
    use super::*;
    use crate::types::describe::{FieldDescribe, FieldType, SObjectDescribe};
    use std::collections::HashMap;

    fn mock_field(name: &str, type_: FieldType) -> FieldDescribe {
        FieldDescribe {
            aggregatable: true,
            auto_number: false,
            byte_length: 0,
            calculated: false,
            calculated_formula: None,
            cascade_delete: false,
            case_sensitive: false,
            compound_field_name: None,
            controller_name: None,
            createable: true,
            custom: false,
            default_value: None,
            default_value_formula: None,
            defaulted_on_create: false,
            dependent_picklist: false,
            deprecated_and_hidden: false,
            digits: 0,
            display_location_in_decimal: false,
            encrypted: false,
            external_id: false,
            extra_type_info: None,
            filterable: true,
            filtered_lookup_info: None,
            formula_treat_blanks_as: None,
            groupable: true,
            high_scale_number: false,
            html_formatted: false,
            id_lookup: false,
            inline_help_text: None,
            label: name.to_string(),
            length: 255,
            mask: None,
            mask_type: None,
            name: name.to_string(),
            name_field: false,
            name_pointing: false,
            nillable: true,
            permissionable: true,
            picklist_values: None,
            polymorphic_foreign_key: false,
            precision: 0,
            query_by_distance: false,
            reference_target_field: None,
            reference_to: vec![],
            relationship_name: None,
            relationship_order: None,
            restricted_delete: false,
            restricted_picklist: false,
            scale: 0,
            search_prefixes_supported: None,
            soap_type: "xsd:string".to_string(),
            sortable: true,
            type_,
            unique: false,
            updateable: true,
            write_requires_master_read: false,
        }
    }

    #[test]
    fn test_generate_apex_class() {
        let describe = SObjectDescribe {
            activateable: false,
            createable: true,
            custom: true,
            custom_setting: false,
            deletable: true,
            deprecated_and_hidden: false,
            feed_enabled: false,
            has_subtypes: false,
            is_subtype: false,
            key_prefix: Some("a00".to_string()),
            label: "Custom Object".to_string(),
            label_plural: "Custom Objects".to_string(),
            layoutable: true,
            mergeable: false,
            mru_enabled: true,
            name: "Custom_Object__c".to_string(),
            queryable: true,
            replicateable: true,
            retrieveable: true,
            searchable: true,
            triggerable: true,
            undeletable: true,
            updateable: true,
            urls: HashMap::new(),
            child_relationships: vec![],
            record_type_infos: vec![],
            fields: vec![
                mock_field("Id", FieldType::Id),
                mock_field("Name", FieldType::String),
                mock_field("Amount__c", FieldType::Currency),
                mock_field("IsActive__c", FieldType::Boolean),
            ],
        };

        let apex = generate_apex_class(&describe);

        assert!(apex.contains("public class Custom_ObjectWrapper {"));
        assert!(apex.contains("public Id Id;"));
        assert!(apex.contains("public String Name;"));
        assert!(apex.contains("public Decimal Amount__c;"));
        assert!(apex.contains("public Boolean IsActive__c;"));
        assert!(apex.contains("@AuraEnabled"));
    }
}
