#[cfg(feature = "schema")]
use crate::types::describe::{FieldType, SObjectDescribe};
use std::fmt::Write;

/// Generates an Apex wrapper class from an SObject describe result.
#[cfg(feature = "schema")]
pub fn generate_apex_wrapper(describe: &SObjectDescribe) -> String {
    let mut out = String::with_capacity(describe.fields.len() * 128);
    write_apex_wrapper(&mut out, describe);
    out
}

/// Writes an Apex wrapper class directly to a buffer.
#[cfg(feature = "schema")]
pub fn write_apex_wrapper(out: &mut String, describe: &SObjectDescribe) {
    let class_name = pascal_case(&describe.name);
    let _ = writeln!(out, "/**");
    let _ = writeln!(out, " * {}", describe.label);
    let _ = writeln!(out, " * Auto-generated by force-rs");
    let _ = writeln!(out, " */");
    let _ = writeln!(out, "public with sharing class {} {{", class_name);

    let mut fields: Vec<&_> = describe.fields.iter().collect();
    fields.sort_by(|a, b| {
        if a.name == "Id" {
            std::cmp::Ordering::Less
        } else if b.name == "Id" {
            std::cmp::Ordering::Greater
        } else {
            a.name.cmp(&b.name)
        }
    });

    for field in fields {
        let apex_type = map_type(&field.type_);
        let _ = writeln!(out, "    @AuraEnabled");
        let _ = writeln!(
            out,
            "    public {} {} {{ get; set; }}",
            apex_type, field.name
        );
        out.push('\n');
    }

    out.push_str("}\n");
}

#[cfg(feature = "schema")]
fn pascal_case(s: &str) -> String {
    let mut result = String::with_capacity(s.len());
    let mut capitalize_next = true;
    for c in s.chars() {
        if c == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(c.to_ascii_uppercase());
            capitalize_next = false;
        } else {
            result.push(c);
        }
    }
    result
}

#[cfg(feature = "schema")]
fn map_type(ft: &FieldType) -> &'static str {
    match ft {
        FieldType::Boolean => "Boolean",
        FieldType::Int => "Integer",
        FieldType::Double | FieldType::Currency | FieldType::Percent => "Decimal",
        FieldType::Id | FieldType::Reference => "Id",
        FieldType::Date => "Date",
        FieldType::Datetime => "Datetime",
        FieldType::Time => "Time",
        FieldType::Base64 => "Blob",
        _ => "String",
    }
}

#[cfg(all(test, feature = "schema"))]
mod tests {
    use super::*;
    use crate::test_utils::mock_describe::{MockFieldDescribeBuilder, MockSObjectDescribeBuilder};

    #[test]
    fn test_generate_apex_wrapper() {
        let describe = MockSObjectDescribeBuilder::new("Account")
            .field(MockFieldDescribeBuilder::new("Id", FieldType::Id).build())
            .field(MockFieldDescribeBuilder::new("Name", FieldType::String).build())
            .field(MockFieldDescribeBuilder::new("AnnualRevenue", FieldType::Currency).build())
            .build();

        let result = generate_apex_wrapper(&describe);
        assert!(result.contains("public with sharing class Account {"));
        assert!(result.contains("public Id Id { get; set; }"));
        assert!(result.contains("public String Name { get; set; }"));
        assert!(result.contains("public Decimal AnnualRevenue { get; set; }"));
        assert!(result.contains("@AuraEnabled"));
    }
}
