use crate::types::describe::{FieldType, SObjectDescribe};
use std::fmt::Write;

/// Options for generating Salesforce prompt templates.
#[derive(Debug, Clone)]
pub struct PromptTemplateOptions {
    /// Whether to include field labels as descriptions.
    pub include_descriptions: bool,
    /// Target LLM architecture hint (e.g., "claude", "gpt4").
    pub target_model: Option<String>,
}

impl Default for PromptTemplateOptions {
    fn default() -> Self {
        Self {
            include_descriptions: true,
            target_model: None,
        }
    }
}

/// Generates a prompt template for asking an LLM to generate records of a given SObject.
pub fn generate_data_generation_prompt(
    describe: &SObjectDescribe,
    options: &PromptTemplateOptions,
) -> String {
    let mut prompt = String::new();

    // We want the prompt to ask the LLM to generate realistic mock data.
    let _ = writeln!(
        prompt,
        "You are a helpful AI assistant tasked with generating realistic mock data for Salesforce."
    );
    let _ = writeln!(
        prompt,
        "Please generate a JSON array of mock records for the SObject `{}` ({}).",
        describe.name, describe.label
    );
    let _ = writeln!(
        prompt,
        "Ensure the data aligns with the following schema constraints:\n"
    );

    for field in &describe.fields {
        // Skip some fields that shouldn't typically be generated by LLMs (read-only/system)
        if !field.createable {
            continue;
        }

        let mut constraints = Vec::new();
        if !field.nillable {
            constraints.push("required".to_string());
        }
        if field.unique {
            constraints.push("unique".to_string());
        }

        // len is i32
        if field.length > 0 && field.type_ == FieldType::String {
            constraints.push(format!("max length {}", field.length));
        }

        let type_str = match field.type_ {
            FieldType::Reference => "ID (reference)",
            FieldType::Id => "Salesforce ID",
            FieldType::Boolean => "Boolean",
            FieldType::Int | FieldType::Double | FieldType::Currency | FieldType::Percent => "Number",
            FieldType::Date | FieldType::Datetime => "Date/Time (ISO 8601)",
            _ => "String",
        };

        let constraint_str = if constraints.is_empty() {
            String::new()
        } else {
            format!(" [{}]", constraints.join(", "))
        };

        let desc_str = if options.include_descriptions {
            format!(" // {}", field.label)
        } else {
            String::new()
        };

        let _ = writeln!(
            prompt,
            "- `{}`: {}{}{}",
            field.name, type_str, constraint_str, desc_str
        );
    }

    let _ = writeln!(
        prompt,
        "\nReturn ONLY valid JSON matching this schema, without any markdown formatting or explanations."
    );

    prompt
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_utils::must::Must;
    use serde_json::json;

    fn mock_describe() -> SObjectDescribe {
        let json = json!({
            "name": "Contact",
            "label": "Contact",
            "custom": false,
            "queryable": true,
            "activateable": false, "createable": true, "customSetting": false, "deletable": true,
            "deprecatedAndHidden": false, "feedEnabled": true, "hasSubtypes": false,
            "isSubtype": false, "keyPrefix": "003", "labelPlural": "Contacts", "layoutable": true,
            "mergeable": true, "mruEnabled": true, "replicateable": true, "retrieveable": true,
            "searchable": true, "triggerable": true, "undeletable": true, "updateable": true,
            "urls": {}, "recordTypeInfos": [], "childRelationships": [],
            "fields": [
                {
                    "name": "Id", "type": "id", "label": "Record ID", "custom": false, "nillable": false,
                    "unique": false, "externalId": false, "calculated": false, "referenceTo": [],
                    "aggregatable": true, "autoNumber": false, "byteLength": 18, "cascadeDelete": false,
                    "caseSensitive": false, "createable": false, "defaultedOnCreate": true, "dependentPicklist": false,
                    "deprecatedAndHidden": false, "digits": 0, "displayLocationInDecimal": false, "encrypted": false,
                    "filterable": true, "groupable": true, "highScaleNumber": false, "htmlFormatted": false,
                    "idLookup": true, "length": 18, "nameField": false, "namePointing": false, "permissionable": false,
                    "polymorphicForeignKey": false, "precision": 0, "queryByDistance": false, "restrictedDelete": false,
                    "restrictedPicklist": false, "scale": 0, "soapType": "tns:ID", "sortable": true, "updateable": false,
                    "writeRequiresMasterRead": false
                },
                {
                    "name": "FirstName", "type": "string", "label": "First Name", "custom": false, "nillable": true,
                    "unique": false, "externalId": false, "calculated": false, "referenceTo": [],
                    "aggregatable": true, "autoNumber": false, "byteLength": 40, "cascadeDelete": false,
                    "caseSensitive": false, "createable": true, "defaultedOnCreate": false, "dependentPicklist": false,
                    "deprecatedAndHidden": false, "digits": 0, "displayLocationInDecimal": false, "encrypted": false,
                    "filterable": true, "groupable": true, "highScaleNumber": false, "htmlFormatted": false,
                    "idLookup": false, "length": 40, "nameField": true, "namePointing": false, "permissionable": false,
                    "polymorphicForeignKey": false, "precision": 0, "queryByDistance": false, "restrictedDelete": false,
                    "restrictedPicklist": false, "scale": 0, "soapType": "xsd:string", "sortable": true, "updateable": true,
                    "writeRequiresMasterRead": false
                },
                {
                    "name": "LastName", "type": "string", "label": "Last Name", "custom": false, "nillable": false,
                    "unique": false, "externalId": false, "calculated": false, "referenceTo": [],
                    "aggregatable": true, "autoNumber": false, "byteLength": 80, "cascadeDelete": false,
                    "caseSensitive": false, "createable": true, "defaultedOnCreate": false, "dependentPicklist": false,
                    "deprecatedAndHidden": false, "digits": 0, "displayLocationInDecimal": false, "encrypted": false,
                    "filterable": true, "groupable": true, "highScaleNumber": false, "htmlFormatted": false,
                    "idLookup": false, "length": 80, "nameField": true, "namePointing": false, "permissionable": false,
                    "polymorphicForeignKey": false, "precision": 0, "queryByDistance": false, "restrictedDelete": false,
                    "restrictedPicklist": false, "scale": 0, "soapType": "xsd:string", "sortable": true, "updateable": true,
                    "writeRequiresMasterRead": false
                }
            ]
        });
        serde_json::from_value(json).must()
    }

    #[test]
    fn test_generate_data_generation_prompt() {
        let describe = mock_describe();
        let options = PromptTemplateOptions::default();
        let prompt = generate_data_generation_prompt(&describe, &options);

        // Header check
        assert!(prompt.contains("mock data for Salesforce"));
        assert!(prompt.contains("`Contact` (Contact)"));

        // Field checks (Id should be skipped as it's not createable)
        assert!(!prompt.contains("- `Id`"));

        // FirstName check (optional string)
        assert!(prompt.contains("- `FirstName`: String [max length 40] // First Name"));

        // LastName check (required string)
        assert!(prompt.contains("- `LastName`: String [required, max length 80] // Last Name"));
    }
}
