[package]
name = "force-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros"] }
async-trait = "0.1"

[dependencies.force]
path = ".."
features = ["composite", "rest"]

[[bin]]
name = "fuzz_batch_query"
path = "fuzz_targets/fuzz_batch_query.rs"
test = false
doc = false
bench = false
