//! Data Profiler for Salesforce Records.
//!
//! This module provides the `DataProfiler` utility to analyze actual Salesforce records
//! and generate statistical profiles (null percentages, cardinality, min/max lengths).
//!
//! # The Spark
//! We have `DataValidator` to check outgoing data and `DataMasker` to sanitize it.
//! But what about understanding the *shape* and *quality* of the data itself?
//! `DataProfiler` gives you a statistical summary of your SObject data distributions locally!
//!
//! # Example
//!
//! ```no_run
//! # use force::api::RestOperation;
//! # use force::client::ForceClientBuilder;
//! # use force::data::DataProfiler;
//! # use force::auth::ClientCredentials;
//! # use force::types::DynamicSObject;
//! # #[tokio::main]
//! # async fn main() -> anyhow::Result<()> {
//! # let auth = ClientCredentials::new("id", "secret", "url");
//! # let client = ForceClientBuilder::new().authenticate(auth).build().await?;
//! let mut stream = client.rest().query_stream::<DynamicSObject>("SELECT Id, Name, Industry FROM Account LIMIT 1000");
//!
//! let mut records = Vec::new();
//! while let Some(record) = stream.next().await? {
//!     records.push(record);
//! }
//!
//! let mut profiler = DataProfiler::new();
//! let report = profiler.profile_records(&records);
//!
//! println!("Total records profiled: {}", report.total_records);
//! if let Some(industry_profile) = report.fields.get("Industry") {
//!     println!("Industry Null %: {:.2}%", industry_profile.null_percentage());
//! }
//! # Ok(())
//! # }
//! ```

use crate::types::DynamicSObject;
use serde_json::Value;
use std::collections::{HashMap, HashSet};

/// Statistical profile for a single field.
#[derive(Debug, Default, Clone, PartialEq)]
pub struct FieldProfile {
    /// Total number of records analyzed.
    pub total_records: usize,
    /// Number of records where this field was null or missing.
    pub null_count: usize,
    /// Minimum string length observed (for text fields).
    pub min_length: Option<usize>,
    /// Maximum string length observed (for text fields).
    pub max_length: Option<usize>,
    /// Set of unique values observed (capped at a reasonable limit to avoid OOM).
    pub unique_values: HashSet<String>,
    /// Whether the number of unique values exceeded the tracking limit.
    pub cardinality_exceeded_limit: bool,
}

impl FieldProfile {
    /// Returns the percentage of records where this field is null.
    #[must_use]
    pub fn null_percentage(&self) -> f64 {
        if self.total_records == 0 {
            return 0.0;
        }
        (self.null_count as f64 / self.total_records as f64) * 100.0
    }
}

/// A comprehensive report generated by the `DataProfiler`.
#[derive(Debug, Default, Clone, PartialEq)]
pub struct DataProfileReport {
    /// Total number of records profiled.
    pub total_records: usize,
    /// Individual profiles for each observed field.
    pub fields: HashMap<String, FieldProfile>,
}

/// Utility for profiling data quality and distribution.
#[derive(Debug, Default, Clone)]
pub struct DataProfiler {
    max_unique_tracked: usize,
}

impl DataProfiler {
    /// Creates a new `DataProfiler` with a default cardinality tracking limit of 1000.
    #[must_use]
    pub fn new() -> Self {
        Self {
            max_unique_tracked: 1000,
        }
    }

    /// Sets the maximum number of unique values to track per field (prevents OOM).
    #[must_use]
    pub fn max_unique_tracked(mut self, limit: usize) -> Self {
        self.max_unique_tracked = limit;
        self
    }

    /// Profiles a collection of `DynamicSObject` records.
    #[must_use]
    pub fn profile_records<'a, I>(&self, records: I) -> DataProfileReport
    where
        I: IntoIterator<Item = &'a DynamicSObject>,
    {
        let mut report = DataProfileReport::default();

        for record in records {
            report.total_records += 1;

            if let Some(map) = Some(&record.fields) {
                for (key, value) in map {
                    // Skip internal attributes
                    if key == "attributes" {
                        continue;
                    }

                    let profile = report
                        .fields
                        .entry(key.clone())
                        .or_insert_with(FieldProfile::default);
                    profile.total_records += 1;

                    if value.is_null() {
                        profile.null_count += 1;
                    } else {
                        // Track string lengths
                        if let Some(s) = value.as_str() {
                            let len = s.len();
                            profile.min_length =
                                Some(profile.min_length.map_or(len, |m| m.min(len)));
                            profile.max_length =
                                Some(profile.max_length.map_or(len, |m| m.max(len)));
                        }

                        // Track cardinality
                        let val_str = match value {
                            Value::String(s) => s.clone(),
                            _ => value.to_string(),
                        };

                        if profile.unique_values.len() < self.max_unique_tracked {
                            profile.unique_values.insert(val_str.clone());
                        } else if !profile.unique_values.contains(&val_str) {
                            profile.cardinality_exceeded_limit = true;
                        }
                    }
                }
            }
        }

        report
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::{Attributes, SalesforceId};
    use serde_json::json;

    fn create_mock_record(fields: &serde_json::Value) -> DynamicSObject {
        let dummy_id = SalesforceId::new("001000000000000AAA").unwrap_or_else(|_| unreachable!());
        let attrs = Attributes::new("Account".to_string(), &dummy_id, "v67.0");
        let mut record = DynamicSObject::new(attrs);

        if let Some(map) = fields.as_object() {
            for (k, v) in map {
                record.fields.insert(k.clone(), v.clone());
            }
        }
        record
    }

    #[test]
    fn test_data_profiler_nulls_and_cardinality() {
        let records = vec![
            create_mock_record(&json!({"Name": "Acme", "Industry": "Tech"})),
            create_mock_record(&json!({"Name": "Globex", "Industry": "Manufacturing"})),
            create_mock_record(&json!({"Name": "Initech", "Industry": null})),
            create_mock_record(&json!({"Name": "Stark", "Industry": "Tech"})),
        ];

        let profiler = DataProfiler::new();
        let report = profiler.profile_records(&records);

        assert_eq!(report.total_records, 4);

        let industry = report
            .fields
            .get("Industry")
            .unwrap_or_else(|| unreachable!());
        assert_eq!(industry.total_records, 4);
        assert_eq!(industry.null_count, 1);
        assert!((industry.null_percentage() - 25.0).abs() < f64::EPSILON);
        assert_eq!(industry.unique_values.len(), 2); // Tech, Manufacturing
        assert!(!industry.cardinality_exceeded_limit);
        assert!(industry.unique_values.contains("Tech"));

        let name = report.fields.get("Name").unwrap_or_else(|| unreachable!());
        assert_eq!(name.null_count, 0);
        assert_eq!(name.min_length, Some(4)); // Acme
        assert_eq!(name.max_length, Some(7)); // Initech
    }

    #[test]
    fn test_data_profiler_limits_unique_values() {
        let mut records = Vec::new();
        for i in 0..10 {
            records.push(create_mock_record(&json!({"Counter": i})));
        }

        let profiler = DataProfiler::new().max_unique_tracked(5);
        let report = profiler.profile_records(&records);

        let counter = report
            .fields
            .get("Counter")
            .unwrap_or_else(|| unreachable!());
        assert!(counter.cardinality_exceeded_limit);
        assert_eq!(counter.unique_values.len(), 5); // Capped at 5
    }
}
